import { Inter } from "next/font/google";
import '@fontsource/bebas-neue';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Código Creativo | Agencia de Marketing Digital 💜",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
